// flow-typed signature: ece845811ec3f6b47b94da76faa8779d
// flow-typed version: <<STUB>>/babel-loader_v^8.0.4/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-loader/lib/cache' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/Error' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/index' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/injectCaller' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-loader/lib/cache.js' {
  declare module.exports: $Exports<'babel-loader/lib/cache'>;
}
declare module 'babel-loader/lib/Error.js' {
  declare module.exports: $Exports<'babel-loader/lib/Error'>;
}
declare module 'babel-loader/lib/index.js' {
  declare module.exports: $Exports<'babel-loader/lib/index'>;
}
declare module 'babel-loader/lib/injectCaller.js' {
  declare module.exports: $Exports<'babel-loader/lib/injectCaller'>;
}
declare module 'babel-loader/lib/transform.js' {
  declare module.exports: $Exports<'babel-loader/lib/transform'>;
}
