// flow-typed signature: ea3ebbb9cc9c6fae027849c00441bf11
// flow-typed version: <<STUB>>/babel-plugin-dev-expression_v^0.2.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-dev-expression'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-dev-expression' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-dev-expression/dev-expression' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-dev-expression/dev-expression.js' {
  declare module.exports: $Exports<'babel-plugin-dev-expression/dev-expression'>;
}
