// flow-typed signature: 6a8f78a18b825e43ae78b9b4c02ded44
// flow-typed version: <<STUB>>/emotion_v^9.2.12/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion/dist/emotion.umd.min' {
  declare module.exports: any;
}

declare module 'emotion/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'emotion/dist/index.esm' {
  declare module.exports: any;
}

declare module 'emotion/macro' {
  declare module.exports: any;
}

declare module 'emotion/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion/dist/emotion.umd.min.js' {
  declare module.exports: $Exports<'emotion/dist/emotion.umd.min'>;
}
declare module 'emotion/dist/index.cjs.js' {
  declare module.exports: $Exports<'emotion/dist/index.cjs'>;
}
declare module 'emotion/dist/index.esm.js' {
  declare module.exports: $Exports<'emotion/dist/index.esm'>;
}
declare module 'emotion/macro.js' {
  declare module.exports: $Exports<'emotion/macro'>;
}
declare module 'emotion/src/index.js' {
  declare module.exports: $Exports<'emotion/src/index'>;
}
