// flow-typed signature: ac4aa2e2ad0fd9d822f1f64cec950e7e
// flow-typed version: <<STUB>>/enzyme-adapter-react-15_v^1.0.5/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-adapter-react-15'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-adapter-react-15' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enzyme-adapter-react-15/build/index' {
  declare module.exports: any;
}

declare module 'enzyme-adapter-react-15/build/ReactFifteenAdapter' {
  declare module.exports: any;
}

declare module 'enzyme-adapter-react-15/src/index' {
  declare module.exports: any;
}

declare module 'enzyme-adapter-react-15/src/ReactFifteenAdapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enzyme-adapter-react-15/build/index.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-15/build/index'>;
}
declare module 'enzyme-adapter-react-15/build/ReactFifteenAdapter.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-15/build/ReactFifteenAdapter'>;
}
declare module 'enzyme-adapter-react-15/src/index.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-15/src/index'>;
}
declare module 'enzyme-adapter-react-15/src/ReactFifteenAdapter.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-15/src/ReactFifteenAdapter'>;
}
