// flow-typed signature: 1d4ba71a60a746b531c6c90eb9823226
// flow-typed version: <<STUB>>/eslint-plugin-jest_v^22.7.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jest/lib/__tests__/rules.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/processors/__tests__/snapshot-processor.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/processors/snapshot-processor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/consistent-test-it.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/expect-expect.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/lowercase-name.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-alias-methods.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-commented-out-tests.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-disabled-tests.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-empty-title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-focused-tests.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-hooks.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-identical-title.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-jasmine-globals.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-jest-import.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-large-snapshots.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-mocks-import.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-test-callback.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-test-prefixes.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-test-return-statement.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-truthy-falsy.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-called-with' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-expect-assertions.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-inline-snapshots.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-spy-on.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-strict-equal.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-to-be-null.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-to-be-undefined.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-to-contain.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-to-have-length.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-todo.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/require-tothrow-message.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/valid-describe.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/valid-expect-in-promise.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/valid-expect.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/consistent-test-it' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/expect-expect' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/lowercase-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-alias-methods' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-commented-out-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-disabled-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-empty-title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-focused-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-hooks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-identical-title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-jasmine-globals' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-jest-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-large-snapshots' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-mocks-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-test-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-test-prefixes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-test-return-statement' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-truthy-falsy' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/prefer-called-with' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/prefer-expect-assertions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/prefer-inline-snapshots' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/prefer-spy-on' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/prefer-strict-equal' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/prefer-to-be-null' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/prefer-to-be-undefined' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/prefer-to-contain' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/prefer-to-have-length' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/prefer-todo' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/require-tothrow-message' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/util' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/valid-describe' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/valid-expect-in-promise' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/valid-expect' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/__tests__/rules.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/processors/__tests__/snapshot-processor.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/processors/snapshot-processor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/consistent-test-it.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/expect-expect.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/lowercase-name.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-alias-methods.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-commented-out-tests.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-disabled-tests.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-empty-title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-focused-tests.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-hooks.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-identical-title.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-jasmine-globals.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-jest-import.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-large-snapshots.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-mocks-import.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-test-callback.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-test-prefixes.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-test-return-statement.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/no-truthy-falsy.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-called-with' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-expect-assertions.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-inline-snapshots.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-spy-on.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-strict-equal.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-to-be-null.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-to-be-undefined.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-to-contain.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-to-have-length.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-todo.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/require-tothrow-message.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/valid-describe.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/valid-expect-in-promise.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/__tests__/valid-expect.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/consistent-test-it' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/expect-expect' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/lowercase-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-alias-methods' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-commented-out-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-disabled-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-empty-title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-focused-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-hooks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-identical-title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-jasmine-globals' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-jest-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-large-snapshots' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-mocks-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-test-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-test-prefixes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-test-return-statement' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/no-truthy-falsy' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/prefer-called-with' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/prefer-expect-assertions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/prefer-inline-snapshots' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/prefer-spy-on' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/prefer-strict-equal' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/prefer-to-be-null' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/prefer-to-be-undefined' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/prefer-to-contain' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/prefer-to-have-length' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/prefer-todo' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/require-tothrow-message' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/util' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/valid-describe' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/valid-expect-in-promise' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/src/rules/valid-expect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jest/lib/__tests__/rules.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/__tests__/rules.test'>;
}
declare module 'eslint-plugin-jest/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/index'>;
}
declare module 'eslint-plugin-jest/lib/processors/__tests__/snapshot-processor.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/processors/__tests__/snapshot-processor.test'>;
}
declare module 'eslint-plugin-jest/lib/processors/snapshot-processor.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/processors/snapshot-processor'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/consistent-test-it.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/consistent-test-it.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/expect-expect.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/expect-expect.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/lowercase-name.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/lowercase-name.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-alias-methods.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-alias-methods.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-commented-out-tests.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-commented-out-tests.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-disabled-tests.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-disabled-tests.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-empty-title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-empty-title'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-focused-tests.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-focused-tests.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-hooks.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-hooks.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-identical-title.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-identical-title.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-jasmine-globals.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-jasmine-globals.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-jest-import.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-jest-import.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-large-snapshots.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-large-snapshots.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-mocks-import.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-mocks-import.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-test-callback.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-test-callback.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-test-prefixes.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-test-prefixes.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-test-return-statement.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-test-return-statement.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-truthy-falsy.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-truthy-falsy.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-called-with.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/prefer-called-with'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-expect-assertions.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/prefer-expect-assertions.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-inline-snapshots.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/prefer-inline-snapshots.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-spy-on.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/prefer-spy-on.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-strict-equal.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/prefer-strict-equal.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-to-be-null.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/prefer-to-be-null.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-to-be-undefined.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/prefer-to-be-undefined.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-to-contain.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/prefer-to-contain.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-to-have-length.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/prefer-to-have-length.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/prefer-todo.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/prefer-todo.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/require-tothrow-message.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/require-tothrow-message.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/valid-describe.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/valid-describe.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/valid-expect-in-promise.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/valid-expect-in-promise.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/valid-expect.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/valid-expect.test'>;
}
declare module 'eslint-plugin-jest/lib/rules/consistent-test-it.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/consistent-test-it'>;
}
declare module 'eslint-plugin-jest/lib/rules/expect-expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/expect-expect'>;
}
declare module 'eslint-plugin-jest/lib/rules/lowercase-name.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/lowercase-name'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-alias-methods.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-alias-methods'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-commented-out-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-commented-out-tests'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-disabled-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-disabled-tests'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-empty-title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-empty-title'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-focused-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-focused-tests'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-hooks.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-hooks'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-identical-title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-identical-title'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-jasmine-globals.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-jasmine-globals'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-jest-import.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-jest-import'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-large-snapshots.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-large-snapshots'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-mocks-import.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-mocks-import'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-test-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-test-callback'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-test-prefixes.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-test-prefixes'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-test-return-statement.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-test-return-statement'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-truthy-falsy.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-truthy-falsy'>;
}
declare module 'eslint-plugin-jest/lib/rules/prefer-called-with.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/prefer-called-with'>;
}
declare module 'eslint-plugin-jest/lib/rules/prefer-expect-assertions.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/prefer-expect-assertions'>;
}
declare module 'eslint-plugin-jest/lib/rules/prefer-inline-snapshots.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/prefer-inline-snapshots'>;
}
declare module 'eslint-plugin-jest/lib/rules/prefer-spy-on.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/prefer-spy-on'>;
}
declare module 'eslint-plugin-jest/lib/rules/prefer-strict-equal.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/prefer-strict-equal'>;
}
declare module 'eslint-plugin-jest/lib/rules/prefer-to-be-null.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/prefer-to-be-null'>;
}
declare module 'eslint-plugin-jest/lib/rules/prefer-to-be-undefined.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/prefer-to-be-undefined'>;
}
declare module 'eslint-plugin-jest/lib/rules/prefer-to-contain.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/prefer-to-contain'>;
}
declare module 'eslint-plugin-jest/lib/rules/prefer-to-have-length.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/prefer-to-have-length'>;
}
declare module 'eslint-plugin-jest/lib/rules/prefer-todo.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/prefer-todo'>;
}
declare module 'eslint-plugin-jest/lib/rules/require-tothrow-message.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/require-tothrow-message'>;
}
declare module 'eslint-plugin-jest/lib/rules/util.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/util'>;
}
declare module 'eslint-plugin-jest/lib/rules/valid-describe.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/valid-describe'>;
}
declare module 'eslint-plugin-jest/lib/rules/valid-expect-in-promise.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/valid-expect-in-promise'>;
}
declare module 'eslint-plugin-jest/lib/rules/valid-expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/valid-expect'>;
}
declare module 'eslint-plugin-jest/src/__tests__/rules.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/__tests__/rules.test'>;
}
declare module 'eslint-plugin-jest/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/index'>;
}
declare module 'eslint-plugin-jest/src/processors/__tests__/snapshot-processor.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/processors/__tests__/snapshot-processor.test'>;
}
declare module 'eslint-plugin-jest/src/processors/snapshot-processor.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/processors/snapshot-processor'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/consistent-test-it.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/consistent-test-it.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/expect-expect.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/expect-expect.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/lowercase-name.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/lowercase-name.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-alias-methods.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-alias-methods.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-commented-out-tests.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-commented-out-tests.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-disabled-tests.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-disabled-tests.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-empty-title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-empty-title'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-focused-tests.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-focused-tests.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-hooks.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-hooks.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-identical-title.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-identical-title.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-jasmine-globals.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-jasmine-globals.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-jest-import.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-jest-import.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-large-snapshots.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-large-snapshots.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-mocks-import.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-mocks-import.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-test-callback.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-test-callback.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-test-prefixes.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-test-prefixes.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-test-return-statement.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-test-return-statement.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/no-truthy-falsy.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/no-truthy-falsy.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-called-with.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/prefer-called-with'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-expect-assertions.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/prefer-expect-assertions.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-inline-snapshots.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/prefer-inline-snapshots.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-spy-on.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/prefer-spy-on.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-strict-equal.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/prefer-strict-equal.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-to-be-null.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/prefer-to-be-null.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-to-be-undefined.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/prefer-to-be-undefined.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-to-contain.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/prefer-to-contain.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-to-have-length.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/prefer-to-have-length.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/prefer-todo.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/prefer-todo.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/require-tothrow-message.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/require-tothrow-message.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/valid-describe.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/valid-describe.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/valid-expect-in-promise.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/valid-expect-in-promise.test'>;
}
declare module 'eslint-plugin-jest/src/rules/__tests__/valid-expect.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/__tests__/valid-expect.test'>;
}
declare module 'eslint-plugin-jest/src/rules/consistent-test-it.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/consistent-test-it'>;
}
declare module 'eslint-plugin-jest/src/rules/expect-expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/expect-expect'>;
}
declare module 'eslint-plugin-jest/src/rules/lowercase-name.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/lowercase-name'>;
}
declare module 'eslint-plugin-jest/src/rules/no-alias-methods.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-alias-methods'>;
}
declare module 'eslint-plugin-jest/src/rules/no-commented-out-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-commented-out-tests'>;
}
declare module 'eslint-plugin-jest/src/rules/no-disabled-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-disabled-tests'>;
}
declare module 'eslint-plugin-jest/src/rules/no-empty-title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-empty-title'>;
}
declare module 'eslint-plugin-jest/src/rules/no-focused-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-focused-tests'>;
}
declare module 'eslint-plugin-jest/src/rules/no-hooks.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-hooks'>;
}
declare module 'eslint-plugin-jest/src/rules/no-identical-title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-identical-title'>;
}
declare module 'eslint-plugin-jest/src/rules/no-jasmine-globals.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-jasmine-globals'>;
}
declare module 'eslint-plugin-jest/src/rules/no-jest-import.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-jest-import'>;
}
declare module 'eslint-plugin-jest/src/rules/no-large-snapshots.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-large-snapshots'>;
}
declare module 'eslint-plugin-jest/src/rules/no-mocks-import.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-mocks-import'>;
}
declare module 'eslint-plugin-jest/src/rules/no-test-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-test-callback'>;
}
declare module 'eslint-plugin-jest/src/rules/no-test-prefixes.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-test-prefixes'>;
}
declare module 'eslint-plugin-jest/src/rules/no-test-return-statement.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-test-return-statement'>;
}
declare module 'eslint-plugin-jest/src/rules/no-truthy-falsy.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/no-truthy-falsy'>;
}
declare module 'eslint-plugin-jest/src/rules/prefer-called-with.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/prefer-called-with'>;
}
declare module 'eslint-plugin-jest/src/rules/prefer-expect-assertions.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/prefer-expect-assertions'>;
}
declare module 'eslint-plugin-jest/src/rules/prefer-inline-snapshots.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/prefer-inline-snapshots'>;
}
declare module 'eslint-plugin-jest/src/rules/prefer-spy-on.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/prefer-spy-on'>;
}
declare module 'eslint-plugin-jest/src/rules/prefer-strict-equal.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/prefer-strict-equal'>;
}
declare module 'eslint-plugin-jest/src/rules/prefer-to-be-null.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/prefer-to-be-null'>;
}
declare module 'eslint-plugin-jest/src/rules/prefer-to-be-undefined.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/prefer-to-be-undefined'>;
}
declare module 'eslint-plugin-jest/src/rules/prefer-to-contain.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/prefer-to-contain'>;
}
declare module 'eslint-plugin-jest/src/rules/prefer-to-have-length.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/prefer-to-have-length'>;
}
declare module 'eslint-plugin-jest/src/rules/prefer-todo.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/prefer-todo'>;
}
declare module 'eslint-plugin-jest/src/rules/require-tothrow-message.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/require-tothrow-message'>;
}
declare module 'eslint-plugin-jest/src/rules/util.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/util'>;
}
declare module 'eslint-plugin-jest/src/rules/valid-describe.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/valid-describe'>;
}
declare module 'eslint-plugin-jest/src/rules/valid-expect-in-promise.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/valid-expect-in-promise'>;
}
declare module 'eslint-plugin-jest/src/rules/valid-expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/src/rules/valid-expect'>;
}
