// flow-typed signature: 26b9f634fd35cc1e5a2d9ae95e6840bd
// flow-typed version: <<STUB>>/globby_v^9.1.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'globby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'globby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'globby/gitignore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'globby/gitignore.js' {
  declare module.exports: $Exports<'globby/gitignore'>;
}
declare module 'globby/index' {
  declare module.exports: $Exports<'globby'>;
}
declare module 'globby/index.js' {
  declare module.exports: $Exports<'globby'>;
}
