// flow-typed signature: 4cb2af526618d7982109d75571062aad
// flow-typed version: <<STUB>>/jest-junit_v^6.0.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-junit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-junit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-junit/constants/index' {
  declare module.exports: any;
}

declare module 'jest-junit/utils/buildJsonResults' {
  declare module.exports: any;
}

declare module 'jest-junit/utils/getOptions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-junit/constants/index.js' {
  declare module.exports: $Exports<'jest-junit/constants/index'>;
}
declare module 'jest-junit/index' {
  declare module.exports: $Exports<'jest-junit'>;
}
declare module 'jest-junit/index.js' {
  declare module.exports: $Exports<'jest-junit'>;
}
declare module 'jest-junit/utils/buildJsonResults.js' {
  declare module.exports: $Exports<'jest-junit/utils/buildJsonResults'>;
}
declare module 'jest-junit/utils/getOptions.js' {
  declare module.exports: $Exports<'jest-junit/utils/getOptions'>;
}
