// flow-typed signature: 4d088ad7ea08ca413f7d729ad94d8555
// flow-typed version: <<STUB>>/jest-watch-typeahead_v^0.3.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-watch-typeahead'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-watch-typeahead' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-watch-typeahead/build/file_name_pattern_prompt' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/file_name_plugin' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/file_name_plugin/plugin' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/file_name_plugin/prompt' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/index' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/lib/pattern_mode_helpers' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/lib/scroll' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/lib/utils' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/shared/pattern_mode_helpers' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/shared/scroll' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/test_name_pattern_prompt' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/test_name_plugin' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/test_name_plugin/plugin' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/test_name_plugin/prompt' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/test_utils/pluginTester' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/types/Config' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/filename' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/testname' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-watch-typeahead/build/file_name_pattern_prompt.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/file_name_pattern_prompt'>;
}
declare module 'jest-watch-typeahead/build/file_name_plugin.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/file_name_plugin'>;
}
declare module 'jest-watch-typeahead/build/file_name_plugin/plugin.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/file_name_plugin/plugin'>;
}
declare module 'jest-watch-typeahead/build/file_name_plugin/prompt.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/file_name_plugin/prompt'>;
}
declare module 'jest-watch-typeahead/build/index.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/index'>;
}
declare module 'jest-watch-typeahead/build/lib/pattern_mode_helpers.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/lib/pattern_mode_helpers'>;
}
declare module 'jest-watch-typeahead/build/lib/scroll.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/lib/scroll'>;
}
declare module 'jest-watch-typeahead/build/lib/utils.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/lib/utils'>;
}
declare module 'jest-watch-typeahead/build/shared/pattern_mode_helpers.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/shared/pattern_mode_helpers'>;
}
declare module 'jest-watch-typeahead/build/shared/scroll.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/shared/scroll'>;
}
declare module 'jest-watch-typeahead/build/test_name_pattern_prompt.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/test_name_pattern_prompt'>;
}
declare module 'jest-watch-typeahead/build/test_name_plugin.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/test_name_plugin'>;
}
declare module 'jest-watch-typeahead/build/test_name_plugin/plugin.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/test_name_plugin/plugin'>;
}
declare module 'jest-watch-typeahead/build/test_name_plugin/prompt.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/test_name_plugin/prompt'>;
}
declare module 'jest-watch-typeahead/build/test_utils/pluginTester.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/test_utils/pluginTester'>;
}
declare module 'jest-watch-typeahead/build/types/Config.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/types/Config'>;
}
declare module 'jest-watch-typeahead/filename.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/filename'>;
}
declare module 'jest-watch-typeahead/testname.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/testname'>;
}
