// flow-typed signature: 088dd1ce4f350e47ffb67cbb033ba41f
// flow-typed version: <<STUB>>/jest-watch-typeahead_v^0.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-watch-typeahead'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-watch-typeahead' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-watch-typeahead/build/file_name_pattern_prompt' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/file_name_plugin' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/filename_plugin' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/index' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/lib/utils' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/shared/constants' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/shared/pattern_mode_helpers' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/shared/pattern_prompt' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/shared/Prompt' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/shared/scroll' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/test_name_pattern_prompt' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/test_name_plugin' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/test_path_pattern_prompt' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/test_path_plugin' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/build/types/Config' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/filename' {
  declare module.exports: any;
}

declare module 'jest-watch-typeahead/testname' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-watch-typeahead/build/file_name_pattern_prompt.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/file_name_pattern_prompt'>;
}
declare module 'jest-watch-typeahead/build/file_name_plugin.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/file_name_plugin'>;
}
declare module 'jest-watch-typeahead/build/filename_plugin.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/filename_plugin'>;
}
declare module 'jest-watch-typeahead/build/index.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/index'>;
}
declare module 'jest-watch-typeahead/build/lib/utils.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/lib/utils'>;
}
declare module 'jest-watch-typeahead/build/shared/constants.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/shared/constants'>;
}
declare module 'jest-watch-typeahead/build/shared/pattern_mode_helpers.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/shared/pattern_mode_helpers'>;
}
declare module 'jest-watch-typeahead/build/shared/pattern_prompt.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/shared/pattern_prompt'>;
}
declare module 'jest-watch-typeahead/build/shared/Prompt.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/shared/Prompt'>;
}
declare module 'jest-watch-typeahead/build/shared/scroll.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/shared/scroll'>;
}
declare module 'jest-watch-typeahead/build/test_name_pattern_prompt.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/test_name_pattern_prompt'>;
}
declare module 'jest-watch-typeahead/build/test_name_plugin.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/test_name_plugin'>;
}
declare module 'jest-watch-typeahead/build/test_path_pattern_prompt.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/test_path_pattern_prompt'>;
}
declare module 'jest-watch-typeahead/build/test_path_plugin.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/test_path_plugin'>;
}
declare module 'jest-watch-typeahead/build/types/Config.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/build/types/Config'>;
}
declare module 'jest-watch-typeahead/filename.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/filename'>;
}
declare module 'jest-watch-typeahead/testname.js' {
  declare module.exports: $Exports<'jest-watch-typeahead/testname'>;
}
