// flow-typed signature: 7c9cb95c151c4952ee630312bd96e2bc
// flow-typed version: <<STUB>>/opn-cli_v^3.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opn-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opn-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opn-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opn-cli/cli.js' {
  declare module.exports: $Exports<'opn-cli/cli'>;
}
