// flow-typed signature: f7ad1509309c1a017a05b84f52e956c2
// flow-typed version: <<STUB>>/react-emotion_v^9.2.12/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-emotion/dist/emotion.umd.min' {
  declare module.exports: any;
}

declare module 'react-emotion/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'react-emotion/dist/index.esm' {
  declare module.exports: any;
}

declare module 'react-emotion/macro' {
  declare module.exports: any;
}

declare module 'react-emotion/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-emotion/dist/emotion.umd.min.js' {
  declare module.exports: $Exports<'react-emotion/dist/emotion.umd.min'>;
}
declare module 'react-emotion/dist/index.cjs.js' {
  declare module.exports: $Exports<'react-emotion/dist/index.cjs'>;
}
declare module 'react-emotion/dist/index.esm.js' {
  declare module.exports: $Exports<'react-emotion/dist/index.esm'>;
}
declare module 'react-emotion/macro.js' {
  declare module.exports: $Exports<'react-emotion/macro'>;
}
declare module 'react-emotion/src/index.js' {
  declare module.exports: $Exports<'react-emotion/src/index'>;
}
