// flow-typed signature: 238932b5c52d707f8fab0e73f5d63a24
// flow-typed version: <<STUB>>/rollup-plugin-strip_v^1.2.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-strip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-strip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-strip/dist/rollup-plugin-strip.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-strip/dist/rollup-plugin-strip.es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-strip/dist/rollup-plugin-strip.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-strip/dist/rollup-plugin-strip.cjs'>;
}
declare module 'rollup-plugin-strip/dist/rollup-plugin-strip.es.js' {
  declare module.exports: $Exports<'rollup-plugin-strip/dist/rollup-plugin-strip.es'>;
}
