// flow-typed signature: 717a76d8b894ebfa7257bd5f5416a1b7
// flow-typed version: <<STUB>>/rollup-plugin-size-snapshot_v^0.8.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-size-snapshot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-size-snapshot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-size-snapshot/dist/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/dist/snapshot' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/dist/treeshakeWithRollup' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/dist/treeshakeWithWebpack' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-size-snapshot/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/dist/index'>;
}
declare module 'rollup-plugin-size-snapshot/dist/snapshot.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/dist/snapshot'>;
}
declare module 'rollup-plugin-size-snapshot/dist/treeshakeWithRollup.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/dist/treeshakeWithRollup'>;
}
declare module 'rollup-plugin-size-snapshot/dist/treeshakeWithWebpack.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/dist/treeshakeWithWebpack'>;
}
declare module 'rollup-plugin-size-snapshot/dist/utils.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/dist/utils'>;
}
