// flow-typed signature: 1145fe968af2e90f22f0e2b7af463d7a
// flow-typed version: <<STUB>>/rollup-plugin-size-snapshot_v^0.3.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-size-snapshot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-size-snapshot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-size-snapshot/dist/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/dist/treeshakeWithRollup' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/dist/treeshakeWithWebpack' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/dist/utils' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/src/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/src/treeshakeWithRollup' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/src/treeshakeWithWebpack' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/src/utils' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/tests/fixtures/externals' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/tests/fixtures/pure-annotated' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/tests/fixtures/redux' {
  declare module.exports: any;
}

declare module 'rollup-plugin-size-snapshot/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-size-snapshot/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/dist/index'>;
}
declare module 'rollup-plugin-size-snapshot/dist/treeshakeWithRollup.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/dist/treeshakeWithRollup'>;
}
declare module 'rollup-plugin-size-snapshot/dist/treeshakeWithWebpack.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/dist/treeshakeWithWebpack'>;
}
declare module 'rollup-plugin-size-snapshot/dist/utils.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/dist/utils'>;
}
declare module 'rollup-plugin-size-snapshot/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'rollup-plugin-size-snapshot/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/flow-typed/npm/jest_v22.x.x'>;
}
declare module 'rollup-plugin-size-snapshot/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/flow-typed/npm/prettier_v1.x.x'>;
}
declare module 'rollup-plugin-size-snapshot/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/src/index'>;
}
declare module 'rollup-plugin-size-snapshot/src/treeshakeWithRollup.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/src/treeshakeWithRollup'>;
}
declare module 'rollup-plugin-size-snapshot/src/treeshakeWithWebpack.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/src/treeshakeWithWebpack'>;
}
declare module 'rollup-plugin-size-snapshot/src/utils.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/src/utils'>;
}
declare module 'rollup-plugin-size-snapshot/tests/fixtures/externals.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/tests/fixtures/externals'>;
}
declare module 'rollup-plugin-size-snapshot/tests/fixtures/pure-annotated.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/tests/fixtures/pure-annotated'>;
}
declare module 'rollup-plugin-size-snapshot/tests/fixtures/redux.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/tests/fixtures/redux'>;
}
declare module 'rollup-plugin-size-snapshot/tests/index.test.js' {
  declare module.exports: $Exports<'rollup-plugin-size-snapshot/tests/index.test'>;
}
