// flow-typed signature: fea258f7b4aeef03a92ee293004eb51e
// flow-typed version: <<STUB>>/styled-components_v^4.1.2/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-components/dist/styled-components-macro.cjs' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components-macro.esm' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.browser.cjs' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.browser.esm' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.cjs' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.esm' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.min' {
  declare module.exports: any;
}

declare module 'styled-components/native/dist/styled-components.native.cjs' {
  declare module.exports: any;
}

declare module 'styled-components/native/dist/styled-components.native.esm' {
  declare module.exports: any;
}

declare module 'styled-components/primitives/dist/styled-components-primitives.cjs' {
  declare module.exports: any;
}

declare module 'styled-components/primitives/dist/styled-components-primitives.esm' {
  declare module.exports: any;
}

declare module 'styled-components/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'styled-components/test-utils/index' {
  declare module.exports: any;
}

declare module 'styled-components/test-utils/setupTestFramework' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-components/dist/styled-components-macro.cjs.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components-macro.cjs'>;
}
declare module 'styled-components/dist/styled-components-macro.esm.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components-macro.esm'>;
}
declare module 'styled-components/dist/styled-components.browser.cjs.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.browser.cjs'>;
}
declare module 'styled-components/dist/styled-components.browser.esm.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.browser.esm'>;
}
declare module 'styled-components/dist/styled-components.cjs.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.cjs'>;
}
declare module 'styled-components/dist/styled-components.esm.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.esm'>;
}
declare module 'styled-components/dist/styled-components.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components'>;
}
declare module 'styled-components/dist/styled-components.min.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.min'>;
}
declare module 'styled-components/native/dist/styled-components.native.cjs.js' {
  declare module.exports: $Exports<'styled-components/native/dist/styled-components.native.cjs'>;
}
declare module 'styled-components/native/dist/styled-components.native.esm.js' {
  declare module.exports: $Exports<'styled-components/native/dist/styled-components.native.esm'>;
}
declare module 'styled-components/primitives/dist/styled-components-primitives.cjs.js' {
  declare module.exports: $Exports<'styled-components/primitives/dist/styled-components-primitives.cjs'>;
}
declare module 'styled-components/primitives/dist/styled-components-primitives.esm.js' {
  declare module.exports: $Exports<'styled-components/primitives/dist/styled-components-primitives.esm'>;
}
declare module 'styled-components/scripts/postinstall.js' {
  declare module.exports: $Exports<'styled-components/scripts/postinstall'>;
}
declare module 'styled-components/test-utils/index.js' {
  declare module.exports: $Exports<'styled-components/test-utils/index'>;
}
declare module 'styled-components/test-utils/setupTestFramework.js' {
  declare module.exports: $Exports<'styled-components/test-utils/setupTestFramework'>;
}
