// flow-typed signature: e2e0cee1afa7f626969cc84035053daf
// flow-typed version: <<STUB>>/stylelint-config-prettier_v^5.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-prettier/bin/check' {
  declare module.exports: any;
}

declare module 'stylelint-config-prettier/src/checker' {
  declare module.exports: any;
}

declare module 'stylelint-config-prettier/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-prettier/bin/check.js' {
  declare module.exports: $Exports<'stylelint-config-prettier/bin/check'>;
}
declare module 'stylelint-config-prettier/src/checker.js' {
  declare module.exports: $Exports<'stylelint-config-prettier/src/checker'>;
}
declare module 'stylelint-config-prettier/src/index.js' {
  declare module.exports: $Exports<'stylelint-config-prettier/src/index'>;
}
