// flow-typed signature: ce83ab4f4a322b1fcdd3003ac88c3cb1
// flow-typed version: <<STUB>>/stylelint-config-standard_v^18.2.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-standard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-standard/index' {
  declare module.exports: $Exports<'stylelint-config-standard'>;
}
declare module 'stylelint-config-standard/index.js' {
  declare module.exports: $Exports<'stylelint-config-standard'>;
}
