// flow-typed signature: bb3b1e9d14593b35fa5779ef8ce74889
// flow-typed version: <<STUB>>/testcafe-reporter-xunit_v^2.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testcafe-reporter-xunit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'testcafe-reporter-xunit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testcafe-reporter-xunit/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testcafe-reporter-xunit/lib/index.js' {
  declare module.exports: $Exports<'testcafe-reporter-xunit/lib/index'>;
}
