// flow-typed signature: 768ace8568e98e1a2f697949f930c2d0
// flow-typed version: <<STUB>>/wait-port_v^0.2.6/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wait-port'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wait-port' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wait-port/bin/wait-port' {
  declare module.exports: any;
}

declare module 'wait-port/lib/errors/connection-error' {
  declare module.exports: any;
}

declare module 'wait-port/lib/errors/target-error' {
  declare module.exports: any;
}

declare module 'wait-port/lib/errors/validation-error' {
  declare module.exports: any;
}

declare module 'wait-port/lib/extract-target' {
  declare module.exports: any;
}

declare module 'wait-port/lib/output-functions/dots' {
  declare module.exports: any;
}

declare module 'wait-port/lib/output-functions' {
  declare module.exports: any;
}

declare module 'wait-port/lib/output-functions/silent' {
  declare module.exports: any;
}

declare module 'wait-port/lib/validate-parameters' {
  declare module.exports: any;
}

declare module 'wait-port/lib/wait-port' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wait-port/bin/wait-port.js' {
  declare module.exports: $Exports<'wait-port/bin/wait-port'>;
}
declare module 'wait-port/lib/errors/connection-error.js' {
  declare module.exports: $Exports<'wait-port/lib/errors/connection-error'>;
}
declare module 'wait-port/lib/errors/target-error.js' {
  declare module.exports: $Exports<'wait-port/lib/errors/target-error'>;
}
declare module 'wait-port/lib/errors/validation-error.js' {
  declare module.exports: $Exports<'wait-port/lib/errors/validation-error'>;
}
declare module 'wait-port/lib/extract-target.js' {
  declare module.exports: $Exports<'wait-port/lib/extract-target'>;
}
declare module 'wait-port/lib/output-functions/dots.js' {
  declare module.exports: $Exports<'wait-port/lib/output-functions/dots'>;
}
declare module 'wait-port/lib/output-functions/index' {
  declare module.exports: $Exports<'wait-port/lib/output-functions'>;
}
declare module 'wait-port/lib/output-functions/index.js' {
  declare module.exports: $Exports<'wait-port/lib/output-functions'>;
}
declare module 'wait-port/lib/output-functions/silent.js' {
  declare module.exports: $Exports<'wait-port/lib/output-functions/silent'>;
}
declare module 'wait-port/lib/validate-parameters.js' {
  declare module.exports: $Exports<'wait-port/lib/validate-parameters'>;
}
declare module 'wait-port/lib/wait-port.js' {
  declare module.exports: $Exports<'wait-port/lib/wait-port'>;
}
