// flow-typed signature: 6e78c1a0e2d23daa7bc561562e8a7d24
// flow-typed version: <<STUB>>/wait-port_v^0.2.2/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wait-port'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wait-port' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wait-port/bin/wait-port' {
  declare module.exports: any;
}

declare module 'wait-port/lib/extract-target' {
  declare module.exports: any;
}

declare module 'wait-port/lib/extract-target.spec' {
  declare module.exports: any;
}

declare module 'wait-port/lib/output-functions/dots' {
  declare module.exports: any;
}

declare module 'wait-port/lib/output-functions/dots.spec' {
  declare module.exports: any;
}

declare module 'wait-port/lib/output-functions/index' {
  declare module.exports: any;
}

declare module 'wait-port/lib/output-functions/silent' {
  declare module.exports: any;
}

declare module 'wait-port/lib/validate-parameters' {
  declare module.exports: any;
}

declare module 'wait-port/lib/validate-parameters.spec' {
  declare module.exports: any;
}

declare module 'wait-port/lib/validation-error' {
  declare module.exports: any;
}

declare module 'wait-port/lib/wait-port' {
  declare module.exports: any;
}

declare module 'wait-port/lib/wait-port.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wait-port/bin/wait-port.js' {
  declare module.exports: $Exports<'wait-port/bin/wait-port'>;
}
declare module 'wait-port/lib/extract-target.js' {
  declare module.exports: $Exports<'wait-port/lib/extract-target'>;
}
declare module 'wait-port/lib/extract-target.spec.js' {
  declare module.exports: $Exports<'wait-port/lib/extract-target.spec'>;
}
declare module 'wait-port/lib/output-functions/dots.js' {
  declare module.exports: $Exports<'wait-port/lib/output-functions/dots'>;
}
declare module 'wait-port/lib/output-functions/dots.spec.js' {
  declare module.exports: $Exports<'wait-port/lib/output-functions/dots.spec'>;
}
declare module 'wait-port/lib/output-functions/index.js' {
  declare module.exports: $Exports<'wait-port/lib/output-functions/index'>;
}
declare module 'wait-port/lib/output-functions/silent.js' {
  declare module.exports: $Exports<'wait-port/lib/output-functions/silent'>;
}
declare module 'wait-port/lib/validate-parameters.js' {
  declare module.exports: $Exports<'wait-port/lib/validate-parameters'>;
}
declare module 'wait-port/lib/validate-parameters.spec.js' {
  declare module.exports: $Exports<'wait-port/lib/validate-parameters.spec'>;
}
declare module 'wait-port/lib/validation-error.js' {
  declare module.exports: $Exports<'wait-port/lib/validation-error'>;
}
declare module 'wait-port/lib/wait-port.js' {
  declare module.exports: $Exports<'wait-port/lib/wait-port'>;
}
declare module 'wait-port/lib/wait-port.spec.js' {
  declare module.exports: $Exports<'wait-port/lib/wait-port.spec'>;
}
