// flow-typed signature: 91258a55e0481f70b1fe9cf214c26e11
// flow-typed version: <<STUB>>/@babel/plugin-transform-modules-commonjs_v^7.0.0-beta.54/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-modules-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-modules-commonjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-modules-commonjs/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-modules-commonjs/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-modules-commonjs/lib/index'>;
}
