// flow-typed signature: c1904f48f37d45b6a4f4553c7a85dd95
// flow-typed version: <<STUB>>/@babel/plugin-transform-runtime_v^7.4.4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-runtime/lib/helpers' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-runtime/lib/index' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-runtime/lib/runtime-corejs2-definitions' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-runtime/lib/runtime-corejs3-definitions' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-runtime/lib/helpers.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-runtime/lib/helpers'>;
}
declare module '@babel/plugin-transform-runtime/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-runtime/lib/index'>;
}
declare module '@babel/plugin-transform-runtime/lib/runtime-corejs2-definitions.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-runtime/lib/runtime-corejs2-definitions'>;
}
declare module '@babel/plugin-transform-runtime/lib/runtime-corejs3-definitions.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-runtime/lib/runtime-corejs3-definitions'>;
}
