// flow-typed signature: 022fe11ca1549bf0457a5d3797d110b5
// flow-typed version: <<STUB>>/@babel/runtime-corejs2_v^7.1.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/runtime-corejs2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/runtime-corejs2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/runtime-corejs2/core-js/array/from' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/array/is-array' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/array/of' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/clear-immediate' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/date/now' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/get-iterator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/is-iterable' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/json/stringify' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/map' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/acosh' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/asinh' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/atanh' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/cbrt' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/clz32' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/cosh' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/expm1' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/fround' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/hypot' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/imul' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/log10' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/log1p' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/log2' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/sign' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/sinh' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/tanh' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/math/trunc' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/number/epsilon' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/number/is-finite' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/number/is-integer' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/number/is-nan' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/number/is-safe-integer' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/number/max-safe-integer' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/number/min-safe-integer' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/number/parse-float' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/number/parse-int' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/assign' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/create' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/define-properties' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/define-property' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/entries' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/freeze' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/get-own-property-descriptor' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/get-own-property-descriptors' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/get-own-property-names' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/get-own-property-symbols' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/get-prototype-of' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/is-extensible' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/is-frozen' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/is-sealed' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/is' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/keys' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/prevent-extensions' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/seal' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/set-prototype-of' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/object/values' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/parse-float' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/parse-int' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/promise' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/apply' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/construct' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/define-property' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/delete-property' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/get-own-property-descriptor' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/get-prototype-of' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/get' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/has' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/is-extensible' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/own-keys' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/prevent-extensions' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/set-prototype-of' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/reflect/set' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/set-immediate' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/set' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/string/at' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/string/from-code-point' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/string/raw' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/async-iterator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/for' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/has-instance' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/is-concat-spreadable' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/iterator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/key-for' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/match' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/replace' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/search' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/species' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/split' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/to-primitive' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/to-string-tag' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/symbol/unscopables' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/weak-map' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/core-js/weak-set' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/applyDecoratedDescriptor' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/arrayWithHoles' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/arrayWithoutHoles' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/assertThisInitialized' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/AsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/asyncGeneratorDelegate' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/asyncIterator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/asyncToGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/awaitAsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/AwaitValue' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/classCallCheck' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/classNameTDZError' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/classPrivateFieldGet' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/classPrivateFieldLooseBase' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/classPrivateFieldLooseKey' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/classPrivateFieldSet' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/classStaticPrivateFieldSpecGet' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/classStaticPrivateFieldSpecSet' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/construct' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/createClass' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/decorate' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/defaults' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/defineEnumerableProperties' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/defineProperty' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/applyDecoratedDescriptor' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/arrayWithHoles' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/arrayWithoutHoles' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/assertThisInitialized' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/AsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/asyncGeneratorDelegate' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/asyncIterator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/asyncToGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/awaitAsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/AwaitValue' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/classCallCheck' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/classNameTDZError' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/classPrivateFieldGet' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/classPrivateFieldLooseBase' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/classPrivateFieldLooseKey' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/classPrivateFieldSet' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/classStaticPrivateFieldSpecGet' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/classStaticPrivateFieldSpecSet' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/construct' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/createClass' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/decorate' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/defaults' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/defineEnumerableProperties' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/defineProperty' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/extends' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/get' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/getPrototypeOf' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/inherits' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/inheritsLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/initializerDefineProperty' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/initializerWarningHelper' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/instanceof' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/interopRequireDefault' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/interopRequireWildcard' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/isNativeFunction' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/iterableToArray' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/iterableToArrayLimit' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/iterableToArrayLimitLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/jsx' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/newArrowCheck' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/nonIterableRest' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/nonIterableSpread' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/objectDestructuringEmpty' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/objectSpread' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/objectWithoutProperties' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/objectWithoutPropertiesLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/possibleConstructorReturn' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/readOnlyError' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/set' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/setPrototypeOf' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/skipFirstGeneratorNext' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/slicedToArray' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/slicedToArrayLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/superPropBase' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/taggedTemplateLiteral' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/taggedTemplateLiteralLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/temporalRef' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/temporalUndefined' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/toArray' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/toConsumableArray' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/toPropertyKey' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/typeof' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/wrapAsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/esm/wrapNativeSuper' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/extends' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/get' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/getPrototypeOf' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/inherits' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/inheritsLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/initializerDefineProperty' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/initializerWarningHelper' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/instanceof' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/interopRequireDefault' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/interopRequireWildcard' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/isNativeFunction' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/iterableToArray' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/iterableToArrayLimit' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/iterableToArrayLimitLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/jsx' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/newArrowCheck' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/nonIterableRest' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/nonIterableSpread' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/objectDestructuringEmpty' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/objectSpread' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/objectWithoutProperties' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/objectWithoutPropertiesLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/possibleConstructorReturn' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/readOnlyError' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/set' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/setPrototypeOf' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/skipFirstGeneratorNext' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/slicedToArray' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/slicedToArrayLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/superPropBase' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/taggedTemplateLiteral' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/taggedTemplateLiteralLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/temporalRef' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/temporalUndefined' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/toArray' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/toConsumableArray' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/toPropertyKey' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/typeof' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/wrapAsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/helpers/wrapNativeSuper' {
  declare module.exports: any;
}

declare module '@babel/runtime-corejs2/regenerator/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/runtime-corejs2/core-js/array/from.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/array/from'>;
}
declare module '@babel/runtime-corejs2/core-js/array/is-array.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/array/is-array'>;
}
declare module '@babel/runtime-corejs2/core-js/array/of.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/array/of'>;
}
declare module '@babel/runtime-corejs2/core-js/clear-immediate.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/clear-immediate'>;
}
declare module '@babel/runtime-corejs2/core-js/date/now.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/date/now'>;
}
declare module '@babel/runtime-corejs2/core-js/get-iterator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/get-iterator'>;
}
declare module '@babel/runtime-corejs2/core-js/is-iterable.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/is-iterable'>;
}
declare module '@babel/runtime-corejs2/core-js/json/stringify.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/json/stringify'>;
}
declare module '@babel/runtime-corejs2/core-js/map.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/map'>;
}
declare module '@babel/runtime-corejs2/core-js/math/acosh.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/acosh'>;
}
declare module '@babel/runtime-corejs2/core-js/math/asinh.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/asinh'>;
}
declare module '@babel/runtime-corejs2/core-js/math/atanh.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/atanh'>;
}
declare module '@babel/runtime-corejs2/core-js/math/cbrt.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/cbrt'>;
}
declare module '@babel/runtime-corejs2/core-js/math/clz32.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/clz32'>;
}
declare module '@babel/runtime-corejs2/core-js/math/cosh.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/cosh'>;
}
declare module '@babel/runtime-corejs2/core-js/math/expm1.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/expm1'>;
}
declare module '@babel/runtime-corejs2/core-js/math/fround.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/fround'>;
}
declare module '@babel/runtime-corejs2/core-js/math/hypot.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/hypot'>;
}
declare module '@babel/runtime-corejs2/core-js/math/imul.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/imul'>;
}
declare module '@babel/runtime-corejs2/core-js/math/log10.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/log10'>;
}
declare module '@babel/runtime-corejs2/core-js/math/log1p.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/log1p'>;
}
declare module '@babel/runtime-corejs2/core-js/math/log2.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/log2'>;
}
declare module '@babel/runtime-corejs2/core-js/math/sign.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/sign'>;
}
declare module '@babel/runtime-corejs2/core-js/math/sinh.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/sinh'>;
}
declare module '@babel/runtime-corejs2/core-js/math/tanh.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/tanh'>;
}
declare module '@babel/runtime-corejs2/core-js/math/trunc.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/math/trunc'>;
}
declare module '@babel/runtime-corejs2/core-js/number/epsilon.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/number/epsilon'>;
}
declare module '@babel/runtime-corejs2/core-js/number/is-finite.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/number/is-finite'>;
}
declare module '@babel/runtime-corejs2/core-js/number/is-integer.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/number/is-integer'>;
}
declare module '@babel/runtime-corejs2/core-js/number/is-nan.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/number/is-nan'>;
}
declare module '@babel/runtime-corejs2/core-js/number/is-safe-integer.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/number/is-safe-integer'>;
}
declare module '@babel/runtime-corejs2/core-js/number/max-safe-integer.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/number/max-safe-integer'>;
}
declare module '@babel/runtime-corejs2/core-js/number/min-safe-integer.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/number/min-safe-integer'>;
}
declare module '@babel/runtime-corejs2/core-js/number/parse-float.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/number/parse-float'>;
}
declare module '@babel/runtime-corejs2/core-js/number/parse-int.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/number/parse-int'>;
}
declare module '@babel/runtime-corejs2/core-js/object/assign.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/assign'>;
}
declare module '@babel/runtime-corejs2/core-js/object/create.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/create'>;
}
declare module '@babel/runtime-corejs2/core-js/object/define-properties.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/define-properties'>;
}
declare module '@babel/runtime-corejs2/core-js/object/define-property.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/define-property'>;
}
declare module '@babel/runtime-corejs2/core-js/object/entries.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/entries'>;
}
declare module '@babel/runtime-corejs2/core-js/object/freeze.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/freeze'>;
}
declare module '@babel/runtime-corejs2/core-js/object/get-own-property-descriptor.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/get-own-property-descriptor'>;
}
declare module '@babel/runtime-corejs2/core-js/object/get-own-property-descriptors.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/get-own-property-descriptors'>;
}
declare module '@babel/runtime-corejs2/core-js/object/get-own-property-names.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/get-own-property-names'>;
}
declare module '@babel/runtime-corejs2/core-js/object/get-own-property-symbols.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/get-own-property-symbols'>;
}
declare module '@babel/runtime-corejs2/core-js/object/get-prototype-of.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/get-prototype-of'>;
}
declare module '@babel/runtime-corejs2/core-js/object/is-extensible.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/is-extensible'>;
}
declare module '@babel/runtime-corejs2/core-js/object/is-frozen.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/is-frozen'>;
}
declare module '@babel/runtime-corejs2/core-js/object/is-sealed.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/is-sealed'>;
}
declare module '@babel/runtime-corejs2/core-js/object/is.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/is'>;
}
declare module '@babel/runtime-corejs2/core-js/object/keys.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/keys'>;
}
declare module '@babel/runtime-corejs2/core-js/object/prevent-extensions.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/prevent-extensions'>;
}
declare module '@babel/runtime-corejs2/core-js/object/seal.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/seal'>;
}
declare module '@babel/runtime-corejs2/core-js/object/set-prototype-of.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/set-prototype-of'>;
}
declare module '@babel/runtime-corejs2/core-js/object/values.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/object/values'>;
}
declare module '@babel/runtime-corejs2/core-js/parse-float.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/parse-float'>;
}
declare module '@babel/runtime-corejs2/core-js/parse-int.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/parse-int'>;
}
declare module '@babel/runtime-corejs2/core-js/promise.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/promise'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/apply.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/apply'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/construct.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/construct'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/define-property.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/define-property'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/delete-property.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/delete-property'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/get-own-property-descriptor.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/get-own-property-descriptor'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/get-prototype-of.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/get-prototype-of'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/get.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/get'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/has.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/has'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/is-extensible.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/is-extensible'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/own-keys.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/own-keys'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/prevent-extensions.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/prevent-extensions'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/set-prototype-of.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/set-prototype-of'>;
}
declare module '@babel/runtime-corejs2/core-js/reflect/set.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/reflect/set'>;
}
declare module '@babel/runtime-corejs2/core-js/set-immediate.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/set-immediate'>;
}
declare module '@babel/runtime-corejs2/core-js/set.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/set'>;
}
declare module '@babel/runtime-corejs2/core-js/string/at.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/string/at'>;
}
declare module '@babel/runtime-corejs2/core-js/string/from-code-point.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/string/from-code-point'>;
}
declare module '@babel/runtime-corejs2/core-js/string/raw.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/string/raw'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/async-iterator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/async-iterator'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/for.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/for'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/has-instance.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/has-instance'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/is-concat-spreadable.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/is-concat-spreadable'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/iterator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/iterator'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/key-for.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/key-for'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/match.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/match'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/replace.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/replace'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/search.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/search'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/species.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/species'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/split.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/split'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/to-primitive.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/to-primitive'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/to-string-tag.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/to-string-tag'>;
}
declare module '@babel/runtime-corejs2/core-js/symbol/unscopables.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/symbol/unscopables'>;
}
declare module '@babel/runtime-corejs2/core-js/weak-map.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/weak-map'>;
}
declare module '@babel/runtime-corejs2/core-js/weak-set.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/core-js/weak-set'>;
}
declare module '@babel/runtime-corejs2/helpers/applyDecoratedDescriptor.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/applyDecoratedDescriptor'>;
}
declare module '@babel/runtime-corejs2/helpers/arrayWithHoles.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/arrayWithHoles'>;
}
declare module '@babel/runtime-corejs2/helpers/arrayWithoutHoles.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/arrayWithoutHoles'>;
}
declare module '@babel/runtime-corejs2/helpers/assertThisInitialized.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/assertThisInitialized'>;
}
declare module '@babel/runtime-corejs2/helpers/AsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/AsyncGenerator'>;
}
declare module '@babel/runtime-corejs2/helpers/asyncGeneratorDelegate.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/asyncGeneratorDelegate'>;
}
declare module '@babel/runtime-corejs2/helpers/asyncIterator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/asyncIterator'>;
}
declare module '@babel/runtime-corejs2/helpers/asyncToGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/asyncToGenerator'>;
}
declare module '@babel/runtime-corejs2/helpers/awaitAsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/awaitAsyncGenerator'>;
}
declare module '@babel/runtime-corejs2/helpers/AwaitValue.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/AwaitValue'>;
}
declare module '@babel/runtime-corejs2/helpers/classCallCheck.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/classCallCheck'>;
}
declare module '@babel/runtime-corejs2/helpers/classNameTDZError.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/classNameTDZError'>;
}
declare module '@babel/runtime-corejs2/helpers/classPrivateFieldGet.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/classPrivateFieldGet'>;
}
declare module '@babel/runtime-corejs2/helpers/classPrivateFieldLooseBase.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/classPrivateFieldLooseBase'>;
}
declare module '@babel/runtime-corejs2/helpers/classPrivateFieldLooseKey.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/classPrivateFieldLooseKey'>;
}
declare module '@babel/runtime-corejs2/helpers/classPrivateFieldSet.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/classPrivateFieldSet'>;
}
declare module '@babel/runtime-corejs2/helpers/classStaticPrivateFieldSpecGet.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/classStaticPrivateFieldSpecGet'>;
}
declare module '@babel/runtime-corejs2/helpers/classStaticPrivateFieldSpecSet.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/classStaticPrivateFieldSpecSet'>;
}
declare module '@babel/runtime-corejs2/helpers/construct.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/construct'>;
}
declare module '@babel/runtime-corejs2/helpers/createClass.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/createClass'>;
}
declare module '@babel/runtime-corejs2/helpers/decorate.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/decorate'>;
}
declare module '@babel/runtime-corejs2/helpers/defaults.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/defaults'>;
}
declare module '@babel/runtime-corejs2/helpers/defineEnumerableProperties.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/defineEnumerableProperties'>;
}
declare module '@babel/runtime-corejs2/helpers/defineProperty.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/defineProperty'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/applyDecoratedDescriptor.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/applyDecoratedDescriptor'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/arrayWithHoles.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/arrayWithHoles'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/arrayWithoutHoles.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/arrayWithoutHoles'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/assertThisInitialized.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/assertThisInitialized'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/AsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/AsyncGenerator'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/asyncGeneratorDelegate.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/asyncGeneratorDelegate'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/asyncIterator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/asyncIterator'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/asyncToGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/asyncToGenerator'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/awaitAsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/awaitAsyncGenerator'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/AwaitValue.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/AwaitValue'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/classCallCheck.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/classCallCheck'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/classNameTDZError.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/classNameTDZError'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/classPrivateFieldGet.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/classPrivateFieldGet'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/classPrivateFieldLooseBase.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/classPrivateFieldLooseBase'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/classPrivateFieldLooseKey.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/classPrivateFieldLooseKey'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/classPrivateFieldSet.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/classPrivateFieldSet'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/classStaticPrivateFieldSpecGet.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/classStaticPrivateFieldSpecGet'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/classStaticPrivateFieldSpecSet.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/classStaticPrivateFieldSpecSet'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/construct.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/construct'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/createClass.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/createClass'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/decorate.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/decorate'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/defaults.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/defaults'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/defineEnumerableProperties.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/defineEnumerableProperties'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/defineProperty.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/defineProperty'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/extends.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/extends'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/get.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/get'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/getPrototypeOf.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/getPrototypeOf'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/inherits.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/inherits'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/inheritsLoose.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/inheritsLoose'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/initializerDefineProperty.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/initializerDefineProperty'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/initializerWarningHelper.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/initializerWarningHelper'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/instanceof.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/instanceof'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/interopRequireDefault.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/interopRequireDefault'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/interopRequireWildcard.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/interopRequireWildcard'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/isNativeFunction.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/isNativeFunction'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/iterableToArray.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/iterableToArray'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/iterableToArrayLimit.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/iterableToArrayLimit'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/iterableToArrayLimitLoose.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/iterableToArrayLimitLoose'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/jsx.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/jsx'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/newArrowCheck.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/newArrowCheck'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/nonIterableRest.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/nonIterableRest'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/nonIterableSpread.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/nonIterableSpread'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/objectDestructuringEmpty.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/objectDestructuringEmpty'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/objectSpread.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/objectSpread'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/objectWithoutProperties.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/objectWithoutProperties'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/objectWithoutPropertiesLoose.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/objectWithoutPropertiesLoose'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/possibleConstructorReturn.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/possibleConstructorReturn'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/readOnlyError.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/readOnlyError'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/set.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/set'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/setPrototypeOf.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/setPrototypeOf'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/skipFirstGeneratorNext.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/skipFirstGeneratorNext'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/slicedToArray.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/slicedToArray'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/slicedToArrayLoose.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/slicedToArrayLoose'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/superPropBase.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/superPropBase'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/taggedTemplateLiteral.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/taggedTemplateLiteral'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/taggedTemplateLiteralLoose.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/taggedTemplateLiteralLoose'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/temporalRef.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/temporalRef'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/temporalUndefined.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/temporalUndefined'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/toArray.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/toArray'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/toConsumableArray.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/toConsumableArray'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/toPropertyKey.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/toPropertyKey'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/typeof.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/typeof'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/wrapAsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/wrapAsyncGenerator'>;
}
declare module '@babel/runtime-corejs2/helpers/esm/wrapNativeSuper.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/esm/wrapNativeSuper'>;
}
declare module '@babel/runtime-corejs2/helpers/extends.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/extends'>;
}
declare module '@babel/runtime-corejs2/helpers/get.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/get'>;
}
declare module '@babel/runtime-corejs2/helpers/getPrototypeOf.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/getPrototypeOf'>;
}
declare module '@babel/runtime-corejs2/helpers/inherits.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/inherits'>;
}
declare module '@babel/runtime-corejs2/helpers/inheritsLoose.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/inheritsLoose'>;
}
declare module '@babel/runtime-corejs2/helpers/initializerDefineProperty.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/initializerDefineProperty'>;
}
declare module '@babel/runtime-corejs2/helpers/initializerWarningHelper.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/initializerWarningHelper'>;
}
declare module '@babel/runtime-corejs2/helpers/instanceof.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/instanceof'>;
}
declare module '@babel/runtime-corejs2/helpers/interopRequireDefault.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/interopRequireDefault'>;
}
declare module '@babel/runtime-corejs2/helpers/interopRequireWildcard.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/interopRequireWildcard'>;
}
declare module '@babel/runtime-corejs2/helpers/isNativeFunction.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/isNativeFunction'>;
}
declare module '@babel/runtime-corejs2/helpers/iterableToArray.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/iterableToArray'>;
}
declare module '@babel/runtime-corejs2/helpers/iterableToArrayLimit.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/iterableToArrayLimit'>;
}
declare module '@babel/runtime-corejs2/helpers/iterableToArrayLimitLoose.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/iterableToArrayLimitLoose'>;
}
declare module '@babel/runtime-corejs2/helpers/jsx.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/jsx'>;
}
declare module '@babel/runtime-corejs2/helpers/newArrowCheck.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/newArrowCheck'>;
}
declare module '@babel/runtime-corejs2/helpers/nonIterableRest.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/nonIterableRest'>;
}
declare module '@babel/runtime-corejs2/helpers/nonIterableSpread.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/nonIterableSpread'>;
}
declare module '@babel/runtime-corejs2/helpers/objectDestructuringEmpty.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/objectDestructuringEmpty'>;
}
declare module '@babel/runtime-corejs2/helpers/objectSpread.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/objectSpread'>;
}
declare module '@babel/runtime-corejs2/helpers/objectWithoutProperties.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/objectWithoutProperties'>;
}
declare module '@babel/runtime-corejs2/helpers/objectWithoutPropertiesLoose.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/objectWithoutPropertiesLoose'>;
}
declare module '@babel/runtime-corejs2/helpers/possibleConstructorReturn.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/possibleConstructorReturn'>;
}
declare module '@babel/runtime-corejs2/helpers/readOnlyError.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/readOnlyError'>;
}
declare module '@babel/runtime-corejs2/helpers/set.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/set'>;
}
declare module '@babel/runtime-corejs2/helpers/setPrototypeOf.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/setPrototypeOf'>;
}
declare module '@babel/runtime-corejs2/helpers/skipFirstGeneratorNext.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/skipFirstGeneratorNext'>;
}
declare module '@babel/runtime-corejs2/helpers/slicedToArray.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/slicedToArray'>;
}
declare module '@babel/runtime-corejs2/helpers/slicedToArrayLoose.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/slicedToArrayLoose'>;
}
declare module '@babel/runtime-corejs2/helpers/superPropBase.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/superPropBase'>;
}
declare module '@babel/runtime-corejs2/helpers/taggedTemplateLiteral.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/taggedTemplateLiteral'>;
}
declare module '@babel/runtime-corejs2/helpers/taggedTemplateLiteralLoose.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/taggedTemplateLiteralLoose'>;
}
declare module '@babel/runtime-corejs2/helpers/temporalRef.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/temporalRef'>;
}
declare module '@babel/runtime-corejs2/helpers/temporalUndefined.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/temporalUndefined'>;
}
declare module '@babel/runtime-corejs2/helpers/toArray.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/toArray'>;
}
declare module '@babel/runtime-corejs2/helpers/toConsumableArray.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/toConsumableArray'>;
}
declare module '@babel/runtime-corejs2/helpers/toPropertyKey.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/toPropertyKey'>;
}
declare module '@babel/runtime-corejs2/helpers/typeof.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/typeof'>;
}
declare module '@babel/runtime-corejs2/helpers/wrapAsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/wrapAsyncGenerator'>;
}
declare module '@babel/runtime-corejs2/helpers/wrapNativeSuper.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/helpers/wrapNativeSuper'>;
}
declare module '@babel/runtime-corejs2/regenerator/index.js' {
  declare module.exports: $Exports<'@babel/runtime-corejs2/regenerator/index'>;
}
