// flow-typed signature: 560a2517484e985de18fbd2d5e0a5b1e
// flow-typed version: <<STUB>>/@babel/runtime_v^7.8.4/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/runtime/helpers/applyDecoratedDescriptor' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/arrayWithHoles' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/arrayWithoutHoles' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/assertThisInitialized' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/AsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/asyncGeneratorDelegate' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/asyncIterator' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/asyncToGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/awaitAsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/AwaitValue' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classCallCheck' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classNameTDZError' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classPrivateFieldDestructureSet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classPrivateFieldGet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classPrivateFieldLooseBase' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classPrivateFieldLooseKey' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classPrivateFieldSet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classPrivateMethodGet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classPrivateMethodSet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classStaticPrivateFieldSpecGet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classStaticPrivateFieldSpecSet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classStaticPrivateMethodGet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/classStaticPrivateMethodSet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/construct' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/createClass' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/decorate' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/defaults' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/defineEnumerableProperties' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/defineProperty' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/applyDecoratedDescriptor' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/arrayWithHoles' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/arrayWithoutHoles' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/assertThisInitialized' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/AsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/asyncGeneratorDelegate' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/asyncIterator' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/asyncToGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/awaitAsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/AwaitValue' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classCallCheck' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classNameTDZError' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classPrivateFieldDestructureSet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classPrivateFieldGet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classPrivateFieldLooseBase' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classPrivateFieldLooseKey' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classPrivateFieldSet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classPrivateMethodGet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classPrivateMethodSet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classStaticPrivateFieldSpecGet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classStaticPrivateFieldSpecSet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classStaticPrivateMethodGet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/classStaticPrivateMethodSet' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/construct' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/createClass' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/decorate' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/defaults' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/defineEnumerableProperties' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/defineProperty' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/extends' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/get' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/getPrototypeOf' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/inherits' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/inheritsLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/initializerDefineProperty' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/initializerWarningHelper' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/instanceof' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/interopRequireDefault' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/interopRequireWildcard' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/isNativeFunction' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/iterableToArray' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/iterableToArrayLimit' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/iterableToArrayLimitLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/jsx' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/newArrowCheck' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/nonIterableRest' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/nonIterableSpread' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/objectDestructuringEmpty' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/objectSpread' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/objectSpread2' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/objectWithoutProperties' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/possibleConstructorReturn' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/readOnlyError' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/set' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/setPrototypeOf' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/skipFirstGeneratorNext' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/slicedToArray' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/slicedToArrayLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/superPropBase' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/taggedTemplateLiteral' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/taggedTemplateLiteralLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/tdz' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/temporalRef' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/temporalUndefined' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/toArray' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/toConsumableArray' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/toPrimitive' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/toPropertyKey' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/typeof' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/wrapAsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/wrapNativeSuper' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/esm/wrapRegExp' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/extends' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/get' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/getPrototypeOf' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/inherits' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/inheritsLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/initializerDefineProperty' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/initializerWarningHelper' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/instanceof' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/interopRequireDefault' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/interopRequireWildcard' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/isNativeFunction' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/iterableToArray' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/iterableToArrayLimit' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/iterableToArrayLimitLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/jsx' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/newArrowCheck' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/nonIterableRest' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/nonIterableSpread' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/objectDestructuringEmpty' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/objectSpread' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/objectSpread2' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/objectWithoutProperties' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/objectWithoutPropertiesLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/possibleConstructorReturn' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/readOnlyError' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/set' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/setPrototypeOf' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/skipFirstGeneratorNext' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/slicedToArray' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/slicedToArrayLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/superPropBase' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/taggedTemplateLiteral' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/taggedTemplateLiteralLoose' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/tdz' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/temporalRef' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/temporalUndefined' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/toArray' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/toConsumableArray' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/toPrimitive' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/toPropertyKey' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/typeof' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/wrapAsyncGenerator' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/wrapNativeSuper' {
  declare module.exports: any;
}

declare module '@babel/runtime/helpers/wrapRegExp' {
  declare module.exports: any;
}

declare module '@babel/runtime/regenerator' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/runtime/helpers/applyDecoratedDescriptor.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/applyDecoratedDescriptor'>;
}
declare module '@babel/runtime/helpers/arrayWithHoles.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/arrayWithHoles'>;
}
declare module '@babel/runtime/helpers/arrayWithoutHoles.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/arrayWithoutHoles'>;
}
declare module '@babel/runtime/helpers/assertThisInitialized.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/assertThisInitialized'>;
}
declare module '@babel/runtime/helpers/AsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/AsyncGenerator'>;
}
declare module '@babel/runtime/helpers/asyncGeneratorDelegate.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/asyncGeneratorDelegate'>;
}
declare module '@babel/runtime/helpers/asyncIterator.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/asyncIterator'>;
}
declare module '@babel/runtime/helpers/asyncToGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/asyncToGenerator'>;
}
declare module '@babel/runtime/helpers/awaitAsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/awaitAsyncGenerator'>;
}
declare module '@babel/runtime/helpers/AwaitValue.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/AwaitValue'>;
}
declare module '@babel/runtime/helpers/classCallCheck.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classCallCheck'>;
}
declare module '@babel/runtime/helpers/classNameTDZError.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classNameTDZError'>;
}
declare module '@babel/runtime/helpers/classPrivateFieldDestructureSet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classPrivateFieldDestructureSet'>;
}
declare module '@babel/runtime/helpers/classPrivateFieldGet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classPrivateFieldGet'>;
}
declare module '@babel/runtime/helpers/classPrivateFieldLooseBase.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classPrivateFieldLooseBase'>;
}
declare module '@babel/runtime/helpers/classPrivateFieldLooseKey.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classPrivateFieldLooseKey'>;
}
declare module '@babel/runtime/helpers/classPrivateFieldSet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classPrivateFieldSet'>;
}
declare module '@babel/runtime/helpers/classPrivateMethodGet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classPrivateMethodGet'>;
}
declare module '@babel/runtime/helpers/classPrivateMethodSet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classPrivateMethodSet'>;
}
declare module '@babel/runtime/helpers/classStaticPrivateFieldSpecGet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classStaticPrivateFieldSpecGet'>;
}
declare module '@babel/runtime/helpers/classStaticPrivateFieldSpecSet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classStaticPrivateFieldSpecSet'>;
}
declare module '@babel/runtime/helpers/classStaticPrivateMethodGet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classStaticPrivateMethodGet'>;
}
declare module '@babel/runtime/helpers/classStaticPrivateMethodSet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/classStaticPrivateMethodSet'>;
}
declare module '@babel/runtime/helpers/construct.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/construct'>;
}
declare module '@babel/runtime/helpers/createClass.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/createClass'>;
}
declare module '@babel/runtime/helpers/decorate.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/decorate'>;
}
declare module '@babel/runtime/helpers/defaults.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/defaults'>;
}
declare module '@babel/runtime/helpers/defineEnumerableProperties.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/defineEnumerableProperties'>;
}
declare module '@babel/runtime/helpers/defineProperty.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/defineProperty'>;
}
declare module '@babel/runtime/helpers/esm/applyDecoratedDescriptor.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/applyDecoratedDescriptor'>;
}
declare module '@babel/runtime/helpers/esm/arrayWithHoles.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/arrayWithHoles'>;
}
declare module '@babel/runtime/helpers/esm/arrayWithoutHoles.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/arrayWithoutHoles'>;
}
declare module '@babel/runtime/helpers/esm/assertThisInitialized.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/assertThisInitialized'>;
}
declare module '@babel/runtime/helpers/esm/AsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/AsyncGenerator'>;
}
declare module '@babel/runtime/helpers/esm/asyncGeneratorDelegate.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/asyncGeneratorDelegate'>;
}
declare module '@babel/runtime/helpers/esm/asyncIterator.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/asyncIterator'>;
}
declare module '@babel/runtime/helpers/esm/asyncToGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/asyncToGenerator'>;
}
declare module '@babel/runtime/helpers/esm/awaitAsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/awaitAsyncGenerator'>;
}
declare module '@babel/runtime/helpers/esm/AwaitValue.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/AwaitValue'>;
}
declare module '@babel/runtime/helpers/esm/classCallCheck.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classCallCheck'>;
}
declare module '@babel/runtime/helpers/esm/classNameTDZError.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classNameTDZError'>;
}
declare module '@babel/runtime/helpers/esm/classPrivateFieldDestructureSet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classPrivateFieldDestructureSet'>;
}
declare module '@babel/runtime/helpers/esm/classPrivateFieldGet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classPrivateFieldGet'>;
}
declare module '@babel/runtime/helpers/esm/classPrivateFieldLooseBase.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classPrivateFieldLooseBase'>;
}
declare module '@babel/runtime/helpers/esm/classPrivateFieldLooseKey.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classPrivateFieldLooseKey'>;
}
declare module '@babel/runtime/helpers/esm/classPrivateFieldSet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classPrivateFieldSet'>;
}
declare module '@babel/runtime/helpers/esm/classPrivateMethodGet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classPrivateMethodGet'>;
}
declare module '@babel/runtime/helpers/esm/classPrivateMethodSet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classPrivateMethodSet'>;
}
declare module '@babel/runtime/helpers/esm/classStaticPrivateFieldSpecGet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classStaticPrivateFieldSpecGet'>;
}
declare module '@babel/runtime/helpers/esm/classStaticPrivateFieldSpecSet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classStaticPrivateFieldSpecSet'>;
}
declare module '@babel/runtime/helpers/esm/classStaticPrivateMethodGet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classStaticPrivateMethodGet'>;
}
declare module '@babel/runtime/helpers/esm/classStaticPrivateMethodSet.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/classStaticPrivateMethodSet'>;
}
declare module '@babel/runtime/helpers/esm/construct.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/construct'>;
}
declare module '@babel/runtime/helpers/esm/createClass.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/createClass'>;
}
declare module '@babel/runtime/helpers/esm/decorate.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/decorate'>;
}
declare module '@babel/runtime/helpers/esm/defaults.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/defaults'>;
}
declare module '@babel/runtime/helpers/esm/defineEnumerableProperties.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/defineEnumerableProperties'>;
}
declare module '@babel/runtime/helpers/esm/defineProperty.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/defineProperty'>;
}
declare module '@babel/runtime/helpers/esm/extends.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/extends'>;
}
declare module '@babel/runtime/helpers/esm/get.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/get'>;
}
declare module '@babel/runtime/helpers/esm/getPrototypeOf.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/getPrototypeOf'>;
}
declare module '@babel/runtime/helpers/esm/inherits.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/inherits'>;
}
declare module '@babel/runtime/helpers/esm/inheritsLoose.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/inheritsLoose'>;
}
declare module '@babel/runtime/helpers/esm/initializerDefineProperty.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/initializerDefineProperty'>;
}
declare module '@babel/runtime/helpers/esm/initializerWarningHelper.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/initializerWarningHelper'>;
}
declare module '@babel/runtime/helpers/esm/instanceof.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/instanceof'>;
}
declare module '@babel/runtime/helpers/esm/interopRequireDefault.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/interopRequireDefault'>;
}
declare module '@babel/runtime/helpers/esm/interopRequireWildcard.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/interopRequireWildcard'>;
}
declare module '@babel/runtime/helpers/esm/isNativeFunction.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/isNativeFunction'>;
}
declare module '@babel/runtime/helpers/esm/iterableToArray.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/iterableToArray'>;
}
declare module '@babel/runtime/helpers/esm/iterableToArrayLimit.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/iterableToArrayLimit'>;
}
declare module '@babel/runtime/helpers/esm/iterableToArrayLimitLoose.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/iterableToArrayLimitLoose'>;
}
declare module '@babel/runtime/helpers/esm/jsx.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/jsx'>;
}
declare module '@babel/runtime/helpers/esm/newArrowCheck.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/newArrowCheck'>;
}
declare module '@babel/runtime/helpers/esm/nonIterableRest.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/nonIterableRest'>;
}
declare module '@babel/runtime/helpers/esm/nonIterableSpread.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/nonIterableSpread'>;
}
declare module '@babel/runtime/helpers/esm/objectDestructuringEmpty.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/objectDestructuringEmpty'>;
}
declare module '@babel/runtime/helpers/esm/objectSpread.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/objectSpread'>;
}
declare module '@babel/runtime/helpers/esm/objectSpread2.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/objectSpread2'>;
}
declare module '@babel/runtime/helpers/esm/objectWithoutProperties.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/objectWithoutProperties'>;
}
declare module '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/objectWithoutPropertiesLoose'>;
}
declare module '@babel/runtime/helpers/esm/possibleConstructorReturn.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/possibleConstructorReturn'>;
}
declare module '@babel/runtime/helpers/esm/readOnlyError.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/readOnlyError'>;
}
declare module '@babel/runtime/helpers/esm/set.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/set'>;
}
declare module '@babel/runtime/helpers/esm/setPrototypeOf.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/setPrototypeOf'>;
}
declare module '@babel/runtime/helpers/esm/skipFirstGeneratorNext.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/skipFirstGeneratorNext'>;
}
declare module '@babel/runtime/helpers/esm/slicedToArray.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/slicedToArray'>;
}
declare module '@babel/runtime/helpers/esm/slicedToArrayLoose.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/slicedToArrayLoose'>;
}
declare module '@babel/runtime/helpers/esm/superPropBase.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/superPropBase'>;
}
declare module '@babel/runtime/helpers/esm/taggedTemplateLiteral.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/taggedTemplateLiteral'>;
}
declare module '@babel/runtime/helpers/esm/taggedTemplateLiteralLoose.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/taggedTemplateLiteralLoose'>;
}
declare module '@babel/runtime/helpers/esm/tdz.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/tdz'>;
}
declare module '@babel/runtime/helpers/esm/temporalRef.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/temporalRef'>;
}
declare module '@babel/runtime/helpers/esm/temporalUndefined.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/temporalUndefined'>;
}
declare module '@babel/runtime/helpers/esm/toArray.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/toArray'>;
}
declare module '@babel/runtime/helpers/esm/toConsumableArray.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/toConsumableArray'>;
}
declare module '@babel/runtime/helpers/esm/toPrimitive.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/toPrimitive'>;
}
declare module '@babel/runtime/helpers/esm/toPropertyKey.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/toPropertyKey'>;
}
declare module '@babel/runtime/helpers/esm/typeof.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/typeof'>;
}
declare module '@babel/runtime/helpers/esm/wrapAsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/wrapAsyncGenerator'>;
}
declare module '@babel/runtime/helpers/esm/wrapNativeSuper.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/wrapNativeSuper'>;
}
declare module '@babel/runtime/helpers/esm/wrapRegExp.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/esm/wrapRegExp'>;
}
declare module '@babel/runtime/helpers/extends.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/extends'>;
}
declare module '@babel/runtime/helpers/get.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/get'>;
}
declare module '@babel/runtime/helpers/getPrototypeOf.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/getPrototypeOf'>;
}
declare module '@babel/runtime/helpers/inherits.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/inherits'>;
}
declare module '@babel/runtime/helpers/inheritsLoose.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/inheritsLoose'>;
}
declare module '@babel/runtime/helpers/initializerDefineProperty.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/initializerDefineProperty'>;
}
declare module '@babel/runtime/helpers/initializerWarningHelper.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/initializerWarningHelper'>;
}
declare module '@babel/runtime/helpers/instanceof.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/instanceof'>;
}
declare module '@babel/runtime/helpers/interopRequireDefault.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/interopRequireDefault'>;
}
declare module '@babel/runtime/helpers/interopRequireWildcard.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/interopRequireWildcard'>;
}
declare module '@babel/runtime/helpers/isNativeFunction.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/isNativeFunction'>;
}
declare module '@babel/runtime/helpers/iterableToArray.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/iterableToArray'>;
}
declare module '@babel/runtime/helpers/iterableToArrayLimit.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/iterableToArrayLimit'>;
}
declare module '@babel/runtime/helpers/iterableToArrayLimitLoose.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/iterableToArrayLimitLoose'>;
}
declare module '@babel/runtime/helpers/jsx.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/jsx'>;
}
declare module '@babel/runtime/helpers/newArrowCheck.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/newArrowCheck'>;
}
declare module '@babel/runtime/helpers/nonIterableRest.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/nonIterableRest'>;
}
declare module '@babel/runtime/helpers/nonIterableSpread.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/nonIterableSpread'>;
}
declare module '@babel/runtime/helpers/objectDestructuringEmpty.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/objectDestructuringEmpty'>;
}
declare module '@babel/runtime/helpers/objectSpread.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/objectSpread'>;
}
declare module '@babel/runtime/helpers/objectSpread2.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/objectSpread2'>;
}
declare module '@babel/runtime/helpers/objectWithoutProperties.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/objectWithoutProperties'>;
}
declare module '@babel/runtime/helpers/objectWithoutPropertiesLoose.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/objectWithoutPropertiesLoose'>;
}
declare module '@babel/runtime/helpers/possibleConstructorReturn.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/possibleConstructorReturn'>;
}
declare module '@babel/runtime/helpers/readOnlyError.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/readOnlyError'>;
}
declare module '@babel/runtime/helpers/set.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/set'>;
}
declare module '@babel/runtime/helpers/setPrototypeOf.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/setPrototypeOf'>;
}
declare module '@babel/runtime/helpers/skipFirstGeneratorNext.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/skipFirstGeneratorNext'>;
}
declare module '@babel/runtime/helpers/slicedToArray.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/slicedToArray'>;
}
declare module '@babel/runtime/helpers/slicedToArrayLoose.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/slicedToArrayLoose'>;
}
declare module '@babel/runtime/helpers/superPropBase.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/superPropBase'>;
}
declare module '@babel/runtime/helpers/taggedTemplateLiteral.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/taggedTemplateLiteral'>;
}
declare module '@babel/runtime/helpers/taggedTemplateLiteralLoose.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/taggedTemplateLiteralLoose'>;
}
declare module '@babel/runtime/helpers/tdz.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/tdz'>;
}
declare module '@babel/runtime/helpers/temporalRef.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/temporalRef'>;
}
declare module '@babel/runtime/helpers/temporalUndefined.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/temporalUndefined'>;
}
declare module '@babel/runtime/helpers/toArray.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/toArray'>;
}
declare module '@babel/runtime/helpers/toConsumableArray.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/toConsumableArray'>;
}
declare module '@babel/runtime/helpers/toPrimitive.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/toPrimitive'>;
}
declare module '@babel/runtime/helpers/toPropertyKey.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/toPropertyKey'>;
}
declare module '@babel/runtime/helpers/typeof.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/typeof'>;
}
declare module '@babel/runtime/helpers/wrapAsyncGenerator.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/wrapAsyncGenerator'>;
}
declare module '@babel/runtime/helpers/wrapNativeSuper.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/wrapNativeSuper'>;
}
declare module '@babel/runtime/helpers/wrapRegExp.js' {
  declare module.exports: $Exports<'@babel/runtime/helpers/wrapRegExp'>;
}
declare module '@babel/runtime/regenerator/index' {
  declare module.exports: $Exports<'@babel/runtime/regenerator'>;
}
declare module '@babel/runtime/regenerator/index.js' {
  declare module.exports: $Exports<'@babel/runtime/regenerator'>;
}
