// flow-typed signature: 10ddf02cdac165d908159d1ed9162354
// flow-typed version: <<STUB>>/@atlaskit/css-reset_v1.1.5/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/css-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/css-reset' {
  declare module.exports: any;
}
