// flow-typed signature: 1e37cf34aa5bb445498a3c315113251b
// flow-typed version: <<STUB>>/@atlaskit/css-reset_v^3.0.6/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/css-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/css-reset' {
  declare module.exports: any;
}
