// flow-typed signature: b82e4146df874d06c07be8c6c7c33510
// flow-typed version: <<STUB>>/@storybook/theming_v^5.0.6/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/theming'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/theming' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/theming/dist/animation' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/base' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/create' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/ensure' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/global' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/modules/syntax' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/tests/create.test' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/themes/dark' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/themes/light' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/utils' {
  declare module.exports: any;
}

declare module '@storybook/theming/src/tests/create.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/theming/dist/animation.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/animation'>;
}
declare module '@storybook/theming/dist/base.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/base'>;
}
declare module '@storybook/theming/dist/create.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/create'>;
}
declare module '@storybook/theming/dist/ensure.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/ensure'>;
}
declare module '@storybook/theming/dist/global.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/global'>;
}
declare module '@storybook/theming/dist/index.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/index'>;
}
declare module '@storybook/theming/dist/modules/syntax.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/modules/syntax'>;
}
declare module '@storybook/theming/dist/tests/create.test.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/tests/create.test'>;
}
declare module '@storybook/theming/dist/themes/dark.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/themes/dark'>;
}
declare module '@storybook/theming/dist/themes/light.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/themes/light'>;
}
declare module '@storybook/theming/dist/utils.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/utils'>;
}
declare module '@storybook/theming/src/tests/create.test.js' {
  declare module.exports: $Exports<'@storybook/theming/src/tests/create.test'>;
}
